### ISSUE TITLE
feat: recursive flags

### ISSUE THREAD

**Issue by tobjaw** [go-clix/cli#3]
Hey @sh0rez, greetings from gridX :wave:
Great package. I've migrated a CLI tool of ours away from `cobra` to this and I'm pleased with the simplicity and robustness of it.   
I noticed there seems to be no way to (recursively) define a flag on a parent command and have it show up on the child commands help. For example, there could be a global `--verbose` flag used to show more detailed output which I would define at the the top level, but in order to have it show up on every child, I'd need to redefine it every time.  
[Cobra calls these "Persistent Flags"](https://github.com/spf13/cobra#persistent-flags). Do you have any plans to include such a feature or is this out of scope for this package?  
Cheers :slightly_smiling_face:

**Comment by tombrk** [comment]
Hi, while writing this initially, I skipped persistent flags on purpose, because I was not able to think of an intuitive way how they should work, and also because [Tanka](https://github.com/grafana/tanka) did not need them.

In case we did implement those, we would need to start merging multiple `pflag.FlagSet` instances based on inheritance rules, which would be pretty complex compared to other parts of this library.

Still I see the demand for "global flags", which we also have to some degree in Tanka, but solved it using standard Go features:

https://github.com/grafana/tanka/blob/d7afbd823897fe1381398d982a8c864e8ef0bf49/cmd/tk/workflow.go#L27-L35

This still defines them once, but in a more flexible way, so you can compose shared "flag groups" onto commands that need them.

Would that work for you? If not, I'm happy to reconsider implementing persistent flags to some degree as well

**Comment by tobjaw** [comment]
I see. That's a neat solution, might adopt it! I currently have approached it in a different way, namely recursively visiting every command and setting the flags there, as I already had to recurse into each command for some other purpose. 
No worries w.r.t. to implementing this in the library, one can easily come up with some solution.

**Comment by tombrk** [comment]
Closing for now, as the workaround seems good.

Everybody feel free to comment here if we need to reconsider
